// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: internal/tunnel/tunnel.proto

package tunnel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TunnelServiceClient is the client API for TunnelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TunnelServiceClient interface {
	// Initial handshake, sent from agent to controller on the control connection, before any other messages.
	SendHello(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*HelloResponse, error)
	// Keep alive, sent from the agent to the controller, on control and data connections.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// The agent will call StartRequest() when it wants the controller to perform
	// an HTTP fetch.
	StartTunnel(ctx context.Context, in *TunnelRequest, opts ...grpc.CallOption) (*TunnelHeaders, error)
	// The agent will perform a long-running call to WaitForRequest() and handle
	// any HTTP request found.
	WaitForRequest(ctx context.Context, in *WaitForRequestRequest, opts ...grpc.CallOption) (*TunnelRequest, error)
	CloseTunnel(ctx context.Context, in *CloseTunnelRequest, opts ...grpc.CallOption) (*CloseTunnelResponse, error)
	// HTTP data, issued from the agent to controller.
	//
	// The Send* methods are when the agent is performing the HTTP request, and
	// wants to send the headers and data response to the controller, which will
	// send it to the client.
	//
	// The Receive* methods are when the controller is performing the HTTP
	// request, and the agent has the client which wants the data.
	SendData(ctx context.Context, in *Data, opts ...grpc.CallOption) (*SendDataResponse, error)
	SendHeaders(ctx context.Context, in *TunnelHeaders, opts ...grpc.CallOption) (*SendHeadersResponse, error)
	ReceiveData(ctx context.Context, in *ReceiveDataRequest, opts ...grpc.CallOption) (*Data, error)
}

type tunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelServiceClient(cc grpc.ClientConnInterface) TunnelServiceClient {
	return &tunnelServiceClient{cc}
}

func (c *tunnelServiceClient) SendHello(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/tunnel.TunnelService/SendHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/tunnel.TunnelService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelServiceClient) StartTunnel(ctx context.Context, in *TunnelRequest, opts ...grpc.CallOption) (*TunnelHeaders, error) {
	out := new(TunnelHeaders)
	err := c.cc.Invoke(ctx, "/tunnel.TunnelService/StartTunnel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelServiceClient) WaitForRequest(ctx context.Context, in *WaitForRequestRequest, opts ...grpc.CallOption) (*TunnelRequest, error) {
	out := new(TunnelRequest)
	err := c.cc.Invoke(ctx, "/tunnel.TunnelService/WaitForRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelServiceClient) CloseTunnel(ctx context.Context, in *CloseTunnelRequest, opts ...grpc.CallOption) (*CloseTunnelResponse, error) {
	out := new(CloseTunnelResponse)
	err := c.cc.Invoke(ctx, "/tunnel.TunnelService/CloseTunnel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelServiceClient) SendData(ctx context.Context, in *Data, opts ...grpc.CallOption) (*SendDataResponse, error) {
	out := new(SendDataResponse)
	err := c.cc.Invoke(ctx, "/tunnel.TunnelService/SendData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelServiceClient) SendHeaders(ctx context.Context, in *TunnelHeaders, opts ...grpc.CallOption) (*SendHeadersResponse, error) {
	out := new(SendHeadersResponse)
	err := c.cc.Invoke(ctx, "/tunnel.TunnelService/SendHeaders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelServiceClient) ReceiveData(ctx context.Context, in *ReceiveDataRequest, opts ...grpc.CallOption) (*Data, error) {
	out := new(Data)
	err := c.cc.Invoke(ctx, "/tunnel.TunnelService/ReceiveData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TunnelServiceServer is the server API for TunnelService service.
// All implementations must embed UnimplementedTunnelServiceServer
// for forward compatibility
type TunnelServiceServer interface {
	// Initial handshake, sent from agent to controller on the control connection, before any other messages.
	SendHello(context.Context, *Hello) (*HelloResponse, error)
	// Keep alive, sent from the agent to the controller, on control and data connections.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// The agent will call StartRequest() when it wants the controller to perform
	// an HTTP fetch.
	StartTunnel(context.Context, *TunnelRequest) (*TunnelHeaders, error)
	// The agent will perform a long-running call to WaitForRequest() and handle
	// any HTTP request found.
	WaitForRequest(context.Context, *WaitForRequestRequest) (*TunnelRequest, error)
	CloseTunnel(context.Context, *CloseTunnelRequest) (*CloseTunnelResponse, error)
	// HTTP data, issued from the agent to controller.
	//
	// The Send* methods are when the agent is performing the HTTP request, and
	// wants to send the headers and data response to the controller, which will
	// send it to the client.
	//
	// The Receive* methods are when the controller is performing the HTTP
	// request, and the agent has the client which wants the data.
	SendData(context.Context, *Data) (*SendDataResponse, error)
	SendHeaders(context.Context, *TunnelHeaders) (*SendHeadersResponse, error)
	ReceiveData(context.Context, *ReceiveDataRequest) (*Data, error)
	mustEmbedUnimplementedTunnelServiceServer()
}

// UnimplementedTunnelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTunnelServiceServer struct {
}

func (UnimplementedTunnelServiceServer) SendHello(context.Context, *Hello) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHello not implemented")
}
func (UnimplementedTunnelServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedTunnelServiceServer) StartTunnel(context.Context, *TunnelRequest) (*TunnelHeaders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTunnel not implemented")
}
func (UnimplementedTunnelServiceServer) WaitForRequest(context.Context, *WaitForRequestRequest) (*TunnelRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitForRequest not implemented")
}
func (UnimplementedTunnelServiceServer) CloseTunnel(context.Context, *CloseTunnelRequest) (*CloseTunnelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseTunnel not implemented")
}
func (UnimplementedTunnelServiceServer) SendData(context.Context, *Data) (*SendDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendData not implemented")
}
func (UnimplementedTunnelServiceServer) SendHeaders(context.Context, *TunnelHeaders) (*SendHeadersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeaders not implemented")
}
func (UnimplementedTunnelServiceServer) ReceiveData(context.Context, *ReceiveDataRequest) (*Data, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveData not implemented")
}
func (UnimplementedTunnelServiceServer) mustEmbedUnimplementedTunnelServiceServer() {}

// UnsafeTunnelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelServiceServer will
// result in compilation errors.
type UnsafeTunnelServiceServer interface {
	mustEmbedUnimplementedTunnelServiceServer()
}

func RegisterTunnelServiceServer(s grpc.ServiceRegistrar, srv TunnelServiceServer) {
	s.RegisterService(&TunnelService_ServiceDesc, srv)
}

func _TunnelService_SendHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).SendHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tunnel.TunnelService/SendHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).SendHello(ctx, req.(*Hello))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tunnel.TunnelService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelService_StartTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).StartTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tunnel.TunnelService/StartTunnel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).StartTunnel(ctx, req.(*TunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelService_WaitForRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitForRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).WaitForRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tunnel.TunnelService/WaitForRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).WaitForRequest(ctx, req.(*WaitForRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelService_CloseTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).CloseTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tunnel.TunnelService/CloseTunnel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).CloseTunnel(ctx, req.(*CloseTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelService_SendData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).SendData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tunnel.TunnelService/SendData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).SendData(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelService_SendHeaders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelHeaders)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).SendHeaders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tunnel.TunnelService/SendHeaders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).SendHeaders(ctx, req.(*TunnelHeaders))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelService_ReceiveData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).ReceiveData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tunnel.TunnelService/ReceiveData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).ReceiveData(ctx, req.(*ReceiveDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TunnelService_ServiceDesc is the grpc.ServiceDesc for TunnelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.TunnelService",
	HandlerType: (*TunnelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHello",
			Handler:    _TunnelService_SendHello_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _TunnelService_Ping_Handler,
		},
		{
			MethodName: "StartTunnel",
			Handler:    _TunnelService_StartTunnel_Handler,
		},
		{
			MethodName: "WaitForRequest",
			Handler:    _TunnelService_WaitForRequest_Handler,
		},
		{
			MethodName: "CloseTunnel",
			Handler:    _TunnelService_CloseTunnel_Handler,
		},
		{
			MethodName: "SendData",
			Handler:    _TunnelService_SendData_Handler,
		},
		{
			MethodName: "SendHeaders",
			Handler:    _TunnelService_SendHeaders_Handler,
		},
		{
			MethodName: "ReceiveData",
			Handler:    _TunnelService_ReceiveData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/tunnel/tunnel.proto",
}
